"""Add rung role

Revision ID: 19199518b0e9
Revises: d623b07804ff
Create Date: 2020-11-21 17:42:58.890361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19199518b0e9'
down_revision = 'd623b07804ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('rung', sa.Integer(), nullable=True))
    op.drop_constraint('player_code_key', 'player', type_='unique')
    op.drop_column('player', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('code', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.create_unique_constraint('player_code_key', 'player', ['code'])
    op.drop_column('player', 'rung')
    # ### end Alembic commands ###
