"""use foreign keys

Revision ID: 2c3efce66502
Revises: 43db4ad67ba2
Create Date: 2021-01-17 18:50:46.304852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3efce66502'
down_revision = '43db4ad67ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'game', 'player', ['host_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['away_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['winner_id'], ['id'])
    op.create_foreign_key(None, 'signup', 'signupmessage', ['signup_id'], ['id'])
    op.create_foreign_key(None, 'signup', 'player', ['player_id'], ['id'])

    op.alter_column('game', 'winner_id', new_column_name='winner')
    op.alter_column('game', 'host_id', new_column_name='host')
    op.alter_column('game', 'away_id', new_column_name='away')
    op.alter_column('signup', 'signup_id', new_column_name='signup')
    op.alter_column('signup', 'player_id', new_column_name='player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'winner', new_column_name='winner_id')
    op.alter_column('game', 'host', new_column_name='host_id')
    op.alter_column('game', 'away', new_column_name='away_id')
    op.alter_column('signup', 'signup', new_column_name='signup_id')
    op.alter_column('signup', 'player', new_column_name='player_id')
    
    op.drop_constraint(None, 'signup', type_='foreignkey')
    op.drop_constraint(None, 'signup', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    # ### end Alembic commands ###
