"""drop unique contraints for igns

Revision ID: 303a2dbfc099
Revises: 3844041321eb
Create Date: 2020-12-04 17:25:44.960063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303a2dbfc099'
down_revision = '3844041321eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_ign_key', 'player', type_='unique')
    op.drop_constraint('player_steam_name_key', 'player', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('player_steam_name_key', 'player', ['steam_name'])
    op.create_unique_constraint('player_ign_key', 'player', ['ign'])
    # ### end Alembic commands ###
