"""Add host_switched field to game

Revision ID: 394a2bf76d9a
Revises: 29d69456e7ef
Create Date: 2021-01-09 12:11:21.868366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394a2bf76d9a'
down_revision = '29d69456e7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('host_switched', sa.Boolean(), default=False, nullable=False))
    op.create_unique_constraint(None, 'gamelog', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gamelog', type_='unique')
    op.drop_column('game', 'host_switched')
    # ### end Alembic commands ###
