"""add name field to player

Revision ID: 43db4ad67ba2
Revises: 5f72131d4154
Create Date: 2021-01-17 15:36:07.123902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43db4ad67ba2'
down_revision = '5f72131d4154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'name')
    # ### end Alembic commands ###
