"""add name, is_started fields to game

Revision ID: 462ee56af406
Revises: 8d4ff34d98ec
Create Date: 2020-10-29 21:13:40.335199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462ee56af406'
down_revision = '8d4ff34d98ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_started', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'name')
    op.drop_column('game', 'is_started')
    # ### end Alembic commands ###
