"""Add close_at field to signupmessage

Revision ID: 4e09b0ad45d6
Revises: b2fa7d95bd5d
Create Date: 2020-11-17 21:26:07.476916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e09b0ad45d6'
down_revision = 'b2fa7d95bd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('close_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup', 'close_at')
    # ### end Alembic commands ###
