"""add active field to player

Revision ID: 616b3d7c8c5f
Revises: be23c6aa9003
Create Date: 2021-01-16 16:20:49.702543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616b3d7c8c5f'
down_revision = 'be23c6aa9003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'active')
    # ### end Alembic commands ###
