"""Add after game step fields to game

Revision ID: 62a3d0b87ad0
Revises: 303a2dbfc099
Create Date: 2020-12-08 17:15:03.805124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a3d0b87ad0'
down_revision = '303a2dbfc099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('away_step_after', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('host_step_after', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'host_step_after')
    op.drop_column('game', 'away_step_after')
    # ### end Alembic commands ###
