"""int to float

Revision ID: 875510aef793
Revises: 9a59a8b4048b
Create Date: 2021-01-20 21:24:18.279403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875510aef793'
down_revision = '9a59a8b4048b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'win_ratio', type_=sa.Float)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'win_ratio', type_=sa.Integer)
    # ### end Alembic commands ###
