"""add autoconfirm fields to game

Revision ID: 8d4ff34d98ec
Revises: 6874a5ca086b
Create Date: 2020-10-29 17:10:39.849981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4ff34d98ec'
down_revision = '6874a5ca086b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('win_claimed_ts', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'game', ['id'])
    op.create_unique_constraint(None, 'player', ['id'])
    op.create_unique_constraint(None, 'signup', ['id'])
    op.create_unique_constraint(None, 'signupmessage', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signupmessage', type_='unique')
    op.drop_constraint(None, 'signup', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_column('game', 'win_claimed_ts')
    op.drop_column('game', 'is_confirmed')
    # ### end Alembic commands ###
