"""add platform field to game

Revision ID: 982673b06691
Revises: 19199518b0e9
Create Date: 2020-12-03 15:25:29.429637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982673b06691'
down_revision = '19199518b0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('mobile', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'mobile')
    # ### end Alembic commands ###
