"""Rename step_after fields to step_change

Revision ID: a422e8412db0
Revises: 62a3d0b87ad0
Create Date: 2020-12-09 12:29:40.199704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a422e8412db0'
down_revision = '62a3d0b87ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'host_step_after', new_column_name='host_step_change')
    op.alter_column('game', 'away_step_after', new_column_name='away_step_change')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'host_step_change', new_column_name='host_step_after')
    op.alter_column('game', 'host_step_chang', new_column_name='host_step_after')
    # ### end Alembic commands ###
