"""make ign/code/steamname unique

Revision ID: b2fa7d95bd5d
Revises: 462ee56af406
Create Date: 2020-10-30 18:31:11.988372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fa7d95bd5d'
down_revision = '462ee56af406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'player', ['ign'])
    op.create_unique_constraint(None, 'player', ['code'])
    op.create_unique_constraint(None, 'player', ['steam_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    # ### end Alembic commands ###
