"""Rename SignupMessage column

Revision ID: b485da6834d9
Revises: 76d3ace6e04e
Create Date: 2020-10-24 17:41:44.990185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b485da6834d9'
down_revision = '76d3ace6e04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signupmessage', 'signups_open', new_column_name='is_open')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signupmessage', 'is_open', new_column_name='signups_open')
    # ### end Alembic commands ###
