"""add win_ratio field

Revision ID: be23c6aa9003
Revises: 394a2bf76d9a
Create Date: 2021-01-16 14:48:11.218658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be23c6aa9003'
down_revision = '394a2bf76d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('win_ratio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'win_ratio')
    # ### end Alembic commands ###
