"""move field across tables

Revision ID: d623b07804ff
Revises: 4e09b0ad45d6
Create Date: 2020-11-18 17:39:23.898591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd623b07804ff'
down_revision = '4e09b0ad45d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup', 'close_at')
    op.add_column('signupmessage', sa.Column('close_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signupmessage', 'close_at')
    op.add_column('signup', sa.Column('close_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
